- blaseball_mike/models.py
As always, credit to baronbliss on the SIBR discord for the equations
> Add player star ratings

- blaseball_mike/models.py
Without this rotation, bullpen, and bench return the lineup players
> Fix team player lists

- blaseball_mike/models.py
- blaseball_mike/tables.py
Some of these might be wrong, I tested it with a couple dozen players. I'm also not a fan of the big if/else chain for converting to strings, but I'm not sure of a better way to do it.
> Add blood, coffee, and weather tables

- blaseball_mike/models.py
- blaseball_mike/tables.py
Not sure if we really need the Attribute descriptions, but I stuck them in there anyway
```python
>>> Player.load_one("86d4e22b-f107-4bcf-9625-32d387fcb521").bat.value
'Vibe Check'
```
> Add Items & Attributes

- blaseball_mike/models.py
Make get_vibes use 1-indexed day like the rest of the library
> Fix Vibes equation

- blaseball_mike/database.py
- blaseball_mike/models.py
I've dug too deep and found new endpoints....
> Add Season, PlayoffMatchup, Standings

- blaseball_mike/tables.py
> Season 6 changes

- blaseball_mike/models.py
- setup.py
> Lazy load team, pitcher, batter on Game object

- blaseball_mike/tables.py
1. Supports items that include modifications (Attributes) like the Fireproof Jacket. 
2. Refactors some of the Tables into a common subclass. Items and Attributes are still special.
3. Fix a minor bug in Item error cases. Players with empty string items should return "None" but players with null items (like incinerated players) should return "None?" in order to match the player page.
At some point we should rename Attribute to Modification to match the site, but I'd rather not break backwards compatibility yet.
> Add Item Modification support

- blaseball_mike/tables.py
> Update for Season 7

- blaseball_mike/models.py
This assumes that rerolls are clamped between 0.01 and 0.99 like buffs are.
> Add reroll to Player simulated_copy

- .idea/.gitignore
Accidentally commited a Pycharm generated file, whoops
> Remove extra gitignore

- blaseball_mike/tables.py
> Updates for Season 8

- blaseball_mike/models.py
- blaseball_mike/tables.py
**Breaking Change**
Just use an Enum rather than rolling our own thing. Lets us do stuff like this:
```python
if Modification.HONEY_ROASTED in player.perm_attr:
print("This player is Honey Roasted")
```
Renamed Attribute to Modification here as well, since it is breaking backwards compat anyway. Not sure if this addresses #23
> Table refactor

- blaseball_mike/tables.py
> Updates for Season 9

- blaseball_mike/tables.py
- setup.py
Fixes #39 
`_missing_` requires Python 3.6 or newer, so setup.py has also been updated.
> Table defaults

- blaseball_mike/tables.py
> More updates for Season 9

- blaseball_mike/database.py
- blaseball_mike/models.py
Interface is basically the same as Idols. Fixes #36.
> Add Hall of Flame Tributes

- blaseball_mike/tables.py
> Yet More Updates for Season 9

- blaseball_mike/models.py
Left the old equations in, but they load from the new ratings if they're available. Also changed `batting` to `hitting` in some places to match the JSON but left in the old ones for backwards compat
> Fix player stat rating and stars

- blaseball_mike/database.py
- requirements.txt
This adds caching using requests_cache. Currently, the expiry on all caches is 5 seconds, though that can be adjusted per-API as needed. Closes #35.
> Add caching

- blaseball_mike/tables.py
lol season's almost over but oh well good enough
> Update for Season 11

- blaseball_mike/database.py
- blaseball_mike/models.py
Been working on unit tests for things, which revealed a couple minor issues
> Various Fixes

- blaseball_mike/database.py
- blaseball_mike/models.py
- blaseball_mike/tables.py
*We are free*
Technically a breaking change, since Player.blood & Player.coffee return the string rather than an Enum. Can still get the numerical value by using Player._blood or Player._coffee.
> Replace Blood & Coffee Tables with endpoint

- blaseball_mike/chronicler.py
- blaseball_mike/database.py
- blaseball_mike/models.py
Added lazy loading for Player `league_team_id` and `tournament_team_id` and the new Game mod stuff, as well as a bunch more unit test discovered fixes.
Biggest change is probably the `Base.json()` stuff, turns out it was including the lazy-loaded objects rather than the keys so `Player.simulated_copy` would break. There isnt really an automatic way to do this, so each class has a function that maps the keys correctly. I even used it as part of the equivalence function since it's actually fairly consistent now.
> Coffee Cup support and minor fixes

- blaseball_mike/chronicler.py
- blaseball_mike/models.py
Chronicler endpoint for getting all games of a tournament (optionally filtered by team)
> add Game.load_by_tournament

- blaseball_mike/tables.py
*crosses fingers that Coffee 3 doesn't show up tomorrow*
> Add Coffee Weathers

- blaseball_mike/models.py
Forgot the minimum bound on patheticism
> Fix Simulated Copy

- blaseball_mike/models.py
> More Player.make_random fixes

- blaseball_mike/models.py
Currently, there is a significant amount of duplicated code for all Lazy Loaded attributes: each needs both a getter and a setter, despite the start of the getter and the entire setter being almost identical for all attributes. This implements a new class decorator `Base.lazy_load` which handles:
* The getters and setters for attached attribute functions
* Optional Caching to a separate attribute
* Optional default value if the attribute doesn't have a value yet
* Optional lookup dictionary generation for mapping back to the original JSON
This should have no functional changes
> Refactor Lazy Loading

- README.md
- blaseball_mike/models.py
- blaseball_mike/tables.py
- docs/blaseball_mike/index.html
- docs/blaseball_mike/models.html
- docs/blaseball_mike/stream_model.html
- docs/blaseball_mike/tables.html
Added some more docs, and fixed a bug in the LazyLoad decorator that caused the code snippets to be broken in the docs
> Documentation updates

- blaseball_mike/tables.py
> Add Coffee 3s

- blaseball_mike/models.py
Some of these changes modify the field return types or ranges which I think means we'd need a major revision
> Various breaking fixups

- blaseball_mike/models.py
Historical Hall of Flame records attempt to fetch the player at the time the hall snapshot was taken, which usually works. However, players incinerated before SIBR performed logging (S2D38ish) do not have records for the entire time the Hall has existed. It looks like between the Hall appearing (~Sept 20) and Sept 25 these players will not exist in chronicler. Since this is a very small amount of time in which none of the incinerated players did anything, just pull the closest player snapshot we can get.
> Fix historical tribute finding no valid player due to archival issues

- .github/workflows/python-test.yml
Now it wont generate a new test every time you make a new release :P
> Only run unit-tests if tested code changes

- blaseball_mike/chronicler.py
add option to return paged results from chroniclers as generators; as to not create memory usage issues with large responses.
i don't know if the way it's implemented is in line with best style practices, but the impl itself is a pretty simple addition
> chronicler results as generators

- blaseball_mike/chronicler.py
Fixes #99 and improves errors for other argument limits as well
> Improve argument validation on Chronicler endpoints

- blaseball_mike/models/player.py
- tests/test_player.py
> New Chorby Soul scream

- blaseball_mike/models/game.py
- blaseball_mike/models/simulation_data.py
- tests/test_game.py
- tests/test_misc.py
Now that we've got some time to breath, add processing on the following fields:
* All the SimulationData phase dates from strings to datetimes
* Game stadium_id to Stadium objects
> New field lazy-loads

- blaseball_mike/models/player.py
> Fix player.load_all

- blaseball_mike/database.py
- blaseball_mike/models/feed.py
Oh hey endpoint field I didnt know existed how are you?
> Add feed filter by event type

- blaseball_mike/tables.py
> Add Salmon weather

- blaseball_mike/database.py
- blaseball_mike/tables.py
* Add a bunch of new endpoints for stuff added in the past few seasons
* Add Sim Phase mappings
> Various Updates

- blaseball_mike/database.py
- blaseball_mike/models/feed.py
* add season parameter to some feed endpoints
* add shopSetup
> Blaseball.com endpoint updates

- blaseball_mike/models/player.py
- blaseball_mike/models/team.py
New getter functions for Player & Team to simplify getting unscattered names. Null teams are still unfixable though, as far as I can tell.
> Add Unscatter helpers

- blaseball_mike/chronicler/v1.py
- blaseball_mike/database.py
- blaseball_mike/models/feed.py
Chronicler and the feed have sim parameters to handle separating the Alternate Universes. Also fix using the wrong paths for the new endpoints.
> Add sim parameters to models & endpoints

- blaseball_mike/database.py
- blaseball_mike/models/league.py
- blaseball_mike/tables.py
* League ID is finally different, so we actually need to load it from the simulation data now
* I made a woopsie when modifying the api calls, fixed `get_weather` (TGB please weather endpoint)
* Added the Exhibition simphase to the list
> Minor Fixes

- blaseball_mike/events.py
This appears to have been missed in the previous updating?
> Update events.py to use api.blaseball.com

- blaseball_mike/database.py
> Fix feed_phase URL

- blaseball_mike/events.py
- requirements.txt
-New streamData has 'delta' events which are applied to the previous event with jsonpatch
> Update streamData processing for Gamma 

- blaseball_mike/eventually.py
adds a batch_size parameter for the eventually wrapper, controlling how many events are fetched at once
> configurable batch size for eventually
